config/routes.rb
Rails.application.routes.draw do
  resources :pizzas

  root to: 'pizzas#home'

  get '/about' => 'pizzas#about'

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json

  def home
  end
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :crust, :sauce, :toppings, :cost, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Pizzashop</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/united/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Pizzas", pizzas_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :crust %><br>
    <%= f.text_field :crust %>
  </div>
  <div class="field">
    <%= f.label :sauce %><br>
    <%= f.text_field :sauce %>
  </div>
  <div class="field">
    <%= f.label :toppings %><br>
    <%= f.text_area :toppings %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/about.html.erb
<div class="jumbotron">

	<center>
		<h1>TMNT Pizza</h1>

		<img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT-I43yylYLUVQ07tovZLoj8MCdxSpdiUs1C5FF28c6aR8K9E9Atg">
		<br>
		<br>

		<h2>Cowlabunga!! We Love Pizza!! Come visit us today!</h2>
	</center>
</div>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/home.html.erb
<div class="jumbotron">

	<center>
		<h1>Welcome to TMNT Pizza!</h1>

		<img src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT-I43yylYLUVQ07tovZLoj8MCdxSpdiUs1C5FF28c6aR8K9E9Atg">
		<br>

		<%= link_to "Check out our Pizzas!", pizzas_path, class: "btn btn-default" %>
	</center>
</div>

app/views/pizzas/index.html.erb
<h1>All of our Pizza's</h1>
<div class="row">
<% @pizzas.each do |pizza| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= pizza.image %>">
      <div class="caption">
        <h3><%= pizza.name %></h3>
        <h3>Cost: $<%= pizza.cost %></h3>
        <%= link_to "More Info", pizza, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>

<%= link_to 'New Pizza', new_pizza_path, class: "btn btn-primary" %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<div class="jumbotron">
  <center>
    <h1><%= @pizza.name %></h1>
    <img src="<%= @pizza.image %>">
  </center>
  <h3>Crust: <%= @pizza.crust %></h3>
  <h3>Sauce: <%= @pizza.sauce %></h3>
  <h3>Toppings: <%= @pizza.toppings %></h3>
  <h3>Cost: $<%= @pizza.cost %></h3>
</div>